export const MusicsData = [
  {
    name: "Army Of  The Dead",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "1a.jpg",
    image: "1.jpg",
    category: "Western",
    language: "English",
    year: "2022",
    time: 5,
    video: "",
    rate: 3.4,
  },
  {
    name: "The Conjuring",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "22.jpeg",
    image: "2.jpeg",
    category: "Thriller",
    language: "Chinese",
    year: "1999",
    time: 6,
    video: "",
    rate: 5,
  },
  {
    name: "My Favorite Person",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "33.jpg",
    image: "3.jpg",
    category: "Adventure",
    language: "Korean",
    year: "2000",
    time: 4,
    video: "",
    rate: 2.5,
  },
  {
    name: "Lets Be a crops",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "44.jpg",
    image: "4.jpg",
    category: "Musicals",
    language: "English",
    year: "2022",
    time: 2,
    video: "",
    rate: 1.5,
  },
  {
    name: "Below her mouth",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "55.jpg",
    image: "5.jpg",
    category: "Romantic",
    language: "English",
    year: "1899",
    time: 3,
    video: "",
    rate: 5,
  },
  {
    name: "Legend of the seeker",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "66.jpg",
    image: "6.jpg",
    category: "Horror",
    language: "Swahili",
    year: "2012",
    time: 12,
    video: "",
    rate: 4.5,
  },
  {
    name: "Scarlet Heart",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "77.jpg",
    image: "7.png",
    category: "Fantasy",
    language: "Korean",
    year: "2005",
    time: 8,
    video: "",
    rate: 0,
  },
  {
    name: "The Last Dance",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "88.jpg",
    image: "8.jpg",
    category: "Sports",
    language: "Japanese",
    year: "1999",
    time: 3,
    video: "",
    rate: 0.5,
  },
  {
    name: "Titanic",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "99.jpg",
    image: "9.jpg",
    category: "Drama",
    language: "Swahili",
    year: "2012",
    time: 14,
    video: "",
    rate: 1,
  },
  {
    name: "About Time of the Dead",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "101.jpg",
    image: "10.jpg",
    category: "Comedy",
    language: "French",
    year: "2000",
    time: 11,
    video: "",
    rate: 0,
  },
  {
    name: "Game of Thrones",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "111.webp",
    image: "11.jpg",
    category: "Action",
    language: "Chinese",
    year: "2012",
    time: 1,
    video: "",
    rate: 1,
  },
];
